setup:
	@composer install
	@generate key
	@copy env file
	@data

composer install:
	composer install

generate key:
	php artisan key:generate

copy env file:
	cp .env.example .env
data:
	php artisan migrate --seed